Repository google/cpu_features, pull requests merged in 2023-09, with the labels that each got.

#328 Add ZEN4 Phoenix detection
  src/impl_x86__base_implementation.inl
  test/cpuinfo_x86_test.cc
Labels: enhancement

#329 Add ZEN4 Genoa detection
  src/impl_x86__base_implementation.inl
  test/cpuinfo_x86_test.cc
Labels: enhancement

#330 Add Intel Alder Lake N detection
  src/impl_x86__base_implementation.inl
  test/cpuinfo_x86_test.cc
Labels: enhancement

#331 Add ZEN2 4800S (CPUID 0880F40)
  src/impl_x86__base_implementation.inl
  test/cpuinfo_x86_test.cc
Labels: enhancement

#334 cmake: Use CpuFeatures:: as TARGET namespace (Fix #333)
  CMakeLists.txt
  cmake/README.md
Labels: bug, cmake

#332 Add Intel AMX-FP16 detection
  include/cpuinfo_x86.h
  src/impl_x86__base_implementation.inl
Labels: enhancement

#339 [misc] Update release script
  scripts/make_release.sh
Labels: misc

#342 fix -Wstrict-prototypes error
  src/hwcaps_linux_or_android.c
Labels: bug, compilation error
