Repository google/cpu_features, pull requests merged in 2023-08, with the labels that each got.

#204 Add support for Apple M1 AArch64 SoCs
  CMakeLists.txt
  README.md
  src/impl_aarch64__base_implementation.inl
  src/impl_aarch64_linux_or_android.c
  src/impl_aarch64_macos_or_iphone.c
  test/CMakeLists.txt
  test/cpuinfo_aarch64_test.cc
Labels: enhancement, Apple M1

#320 Fix bazel for aarch64
  BUILD.bazel
  test/cpuinfo_aarch64_test.cc
Labels: Apple M1, compilation error

#316 Add LoongArch to supported list
  README.md
Labels: documentation

#315 Add Intel LAM/AMD UAI feature detection in X86_64
  include/cpuinfo_x86.h
  src/impl_x86__base_implementation.inl
  test/cpuinfo_x86_test.cc
Labels: enhancement

#325 Add ENABLE_INSTALL option to manage 'install' target
  CMakeLists.txt
Labels: enhancement, cmake

#326 fix generate_badges.d
  scripts/generate_badges.d
Labels: enhancement, documentation

#327 Fix badge shebang and enable badges from workflow files
  scripts/generate_badges.d
Labels: misc
